### ISSUE TITLE
Exception: Failed to execute 'removeEventListener' on 'EventTarget': 2 arguments required, but only 1 present.

### ISSUE THREAD

**Issue by williamwlchen** [Herbis/ngx-bootstrap-feedback#1]
When click on Options.Take Screenshot button on the bottom of the page, the above exception is thrown.

The stack trace:
Failed to execute 'removeEventListener' on 'EventTarget': 2 arguments required, but only 1 present.
    at HTMLDocument.proto.(anonymous function) [as removeEventListener] (webpack-internal:///../../../../zone.js/dist/zone.js:1880:50)
    at Function.FeedbackScreenshotComponent.removeMouseDrawingEvents (webpack-internal:///../../../../ngx-bootstrap-feedback/feedback-screenshot.component.js:305:18)
    at FeedbackScreenshotComponent.takeScreenshot (webpack-internal:///../../../../ngx-bootstrap-feedback/feedback-screenshot.component.js:363:37)
    at FeedbackService.takeScreenshot (webpack-internal:///../../../../ngx-bootstrap-feedback/feedback.service.js:80:34)
    at FeedbackComponent.takeScreenshot (webpack-internal:///../../../../ngx-bootstrap-feedback/feedback.component.js:54:23)

**Comment by Herbis** [comment]
@williamwlchen could you share your dependency list from package.json?

**Comment by williamwlchen** [comment]
@Herbis.
The dependency list is listed below:
There is a discussion about this issue: https://github.com/angular/zone.js/issues/847
it suggests that
"@JiaLiPassion, in zone.js@0.8.5 element.removeEventListener('animationend'); will remove all listeners, but in zone.js@0.8.14 throw error, and element.removeEventListener('animationend', null); will not remove any listener. I used es6, not native javascript"

`
  "dependencies": {
    "@angular/animations": "4.4.3",
    "@angular/common": "4.4.3",
    "@angular/compiler": "4.4.3",
    "@angular/core": "4.4.3",
    "@angular/forms": "4.4.3",
    "@angular/http": "4.4.3",
    "@angular/platform-browser": "4.4.3",
    "@angular/platform-browser-dynamic": "4.4.3",
    "@angular/router": "4.4.3",
    "@herbis/ngx-modal": "0.1.0",
    "bootstrap": "3.3.7",
    "core-js": "^2.4.1",
    "html2canvas": "0.5.0-beta4",
    "jquery": "^3.2.1",
    "ngx-bootstrap": "^2.0.0-beta.6",
    "ngx-bootstrap-feedback": "^1.1.4",
    "rxjs": "5.0.1",
    "zone.js": "^0.8.14"
  },
`

**Comment by Herbis** [comment]
Thanks for the extra info :)
I have just published version "1.1.5-beta1" to npm, could you try it out? I've tested on my own application, but I didn't run into the problem before, so it doesn't say much. 
I'll release 1.1.5 version with this fix if you can confirm it fixes your issue.

**Comment by williamwlchen** [comment]
Downloaded and tested. It is working in version  "1.1.5-beta1". Thank you!

**Comment by Herbis** [comment]
Thank you @williamwlchen .
Version 1.1.5 is available on NPM now.
