### ISSUE TITLE
html2canvas not initialized

### ISSUE THREAD

**Issue by karthikasobhana** [Herbis/ngx-bootstrap-feedback#2]
I am using this package in an Angular 5 project(typescript). 

I have installed npm packages for  "html2canvas": "^0.5.0-beta4", and  "@types/html2canvas": "^0.5.35".
Imported them in the component as below:
       import * as html2canvas from "html2canvas"

 I'm getting the error as "html2canvas not initialized. Please add it to your project or disable 'Take Screenshot' functionality."

Other packages that I included are:
 angular/core: "^5.0.1",
"bootstrap": "^3.3.7",
herbis/ngx-modal: "^0.1.0",
"rxjs": "^5.5.6",

Please help.TIA.

**Comment by Herbis** [comment]
I am no longer in possession of the project I was using this for, so I'll need to set up a new environment to test the way you set it up.
In the mean time,
are you using angular-cli for your project? If so, you might have missed the requirement that the script has to be added to ".angular-cli.json"
https://github.com/Herbis/ngx-bootstrap-feedback#requirements

**Comment by karthikasobhana** [comment]
Oh it is a mistake from my end.. I accidentally included js file for html2canvas as well in angular-cli.json whic was not required. It is working now. :)
